# app.yaml for flex enviroment
    runtime: python27
    env: flex
    entrypoint: gunicorn -b :$PORT main:app

    runtime_config:
      python_version: 2

    handlers:
    - url: /.*
      script: main.app